qp_iter : "qp_iters_"
cost : "get_cost"
merit : "get_merit"
ffeas : "get_gap_norm"
gfeas : "constraint_norm_"
x_step_norm : "get_xgrad_norm"
u_step_norm : "get_ugrad_norm"
step_length : "get_steplength"
KKT : "KKT_"
