qp_iter : "qp_iters"
cost : "cost"
merit : "merit"
ffeas : "gap_norm"
gfeas : "constraint_norm"

###############################
#NEED TO EXPOSE IN MIM_SOLVERS#
###############################

# x_step_norm : "get_xgrad_norm"
# u_step_norm : "get_ugrad_norm"

xs : "xs"
us : "us"
step_length : "stepLength"
KKT : "KKT"
